server:
  port: 5555
spring:
  activemq:
    broker-url: tcp://192.168.108.129:61616 # ActiveMQ服务器的地址和端口
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false：不使用pub-sub，也就是使用queue；true：使用pub-sub，也就是使用topic

#主题的名称
mytopic: boot-activemq-topic
